### ISSUE TITLE
Segfault with Houdini 18.0.566

### ISSUE THREAD

**Issue by o-Dubbie-o** [dimo3d/Cappucino#3]
Hi,
When I open any one of your sample files in Houdini 18.0.566, Houdini segfaults.
This is using your 18.0 prebuilt binary.

**Comment by StefanReinhardt** [comment]
Hey dubbie,
Could you provide some more Info?
I'd be glad to help.
In general you need to copy the Compiled plugin files into the houdini
plugin folder first. Atm i am not100% sure for which Version we Compiled
the Examples but in general it should  work as plug and play for houdini 18
and 19. I will double check the testrun tomorrow morning first thing.
Cheers
Stefan Reinhardt


o-Dubbie-o <notifications@github.com> schrieb am Do., 1. Okt. 2020, 22:44:

**Comment by o-Dubbie-o** [comment]
I have copied the correct DLL into the correct folder as per the README instructions.
I don't know what other info I can give that will help.

**Comment by StefanReinhardt** [comment]
I could reproduce the error. It seem to be a issue with the 18.0 version. In 17.5 it works. We will replace the according dll on zenodo as soon as possible.

**Comment by o-Dubbie-o** [comment]
Thankyou!
While you are at it, would it be possible to build a binary for 18.5 as well?

**Comment by dimo3d** [comment]
I recompiled with 18.0.597 now. Can you test if this solves it?
[Cappucino.zip](https://github.com/dimo3d/Cappucino/files/5317128/Cappucino.zip)
I have no access to 18.5. From the official sidefx page I see only 18.0.xxx versions to download

**Comment by o-Dubbie-o** [comment]
Sorry for the delay in reply. I tried the new build you supplied and it is working fine in Houdini 18.0.566
Thank you for going to the trouble to recompile for me.
